### ISSUE TITLE
compressed responce 

### ISSUE THREAD

**Issue by MrJico** [PostHog/posthog-js#1015]
when using session recording we are unable to access the response data, because the response is compressed(gzip, br), by a third-party    proxy server which doesn't allow content-length which makes session network tab useless.

**Comment by pauldambra** [comment]
Hey @MrJico which proxy server is it?

Is the site public so I can take a look? 

We're very conservative with how we measure payload size because we don't want to break your sites and don't want to ingest giant payloads and delay our ingestion for data that we wouldn't be able to show anyway.

So, without a content-length we don't ingest the payload since we can't (easily/safely) check its size. 

The rest of the network data should still be being collected for you - so it should only be payloads that are missing

**Comment by MrJico** [comment]
unfortunately the website has not been published publicly, but if you want to check just send a dm, i will give you an account to check.

**Comment by pauldambra** [comment]
That'd be great, thanks! Want to open a ticket here https://us.posthog.com/#panel=support%3Asupport%3Asession_replay%3Amedium ? I'm on support rota but it's a safer route than DM if I end up going out sick or something. Thanks!!

**Comment by MrJico** [comment]
done, i will keep this issue open for reference.

**Comment by MrJico** [comment]
no updates from support, can you please verify.

**Comment by pauldambra** [comment]
Hey, on this ticket? https://posthoghelp.zendesk.com/agent/tickets/10455 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/12782)

I asked a few questions on there and was waiting for a response - do let us know if you weren't notified could be zendesk didn't send emails or is ending up in spam.

I actually finished a reasonably large refactor of the payload handling code and released it this morning https://github.com/PostHog/posthog-js/releases/tag/v1.106.1

That has the benefit that since we now know all payloads are strings or absent we don't need to require the content-length any more.

**Comment by MrJico** [comment]
i wasn't notified, i have checked every folder in my mail inbox.

**Comment by pauldambra** [comment]
strange... i've sent another reply on that ticket out of interest to see if it reaches you...

does 1.106.1 work for you?

**Comment by MrJico** [comment]
after updating the issue seems to be resolved  as of [v1.106.1](https://github.com/PostHog/posthog-js/releases/tag/v1.106.1). feel free to close the issue

**Comment by pauldambra** [comment]
great news! thanks for letting us know! I wouldn't have spotted the opportunity to improve this in that PR without the prompt 🔥
