### ISSUE TITLE
CORS issue when proxying posthog to own domain and using custom domains

### ISSUE THREAD

**Issue by mfts** [PostHog/posthog-js#1096]
Analytics aren't logged on custom domains. I'm on a next.js application and using rewrites as a reverse proxy analytics as described in this article: https://posthog.com/docs/advanced/proxy/nextjs

Here's my implementation: 
https://github.com/mfts/papermark/blob/1c96446b9c63f9305460b99a993fecaee81d7376/next.config.mjs#L71-L78

I'm deployed on Vercel and I have custom domains. Everything works well on a papermark.io link. however on a docs.mfts.io link it throws the following CORS error:

```sh
Access to XMLHttpRequest at 'https://www.papermark.io/ingest/e/?retry_count=1&ip=1&_=1711169876868&ver=1.116.0&compression=base64' from origin 'https://docs.mfts.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
_app-c29acf4819a5dbbc.js:15 
        
        
       POST https://www.papermark.io/ingest/e/?retry_count=1&ip=1&_=1711169876868&ver=1.116.0&compression=base64 net::ERR_FAILED
nA @ _app-c29acf4819a5dbbc.js:15
(anonymous) @ _app-c29acf4819a5dbbc.js:15
value @ _app-c29acf4819a5dbbc.js:15
value @ _app-c29acf4819a5dbbc.js:15
value @ _app-c29acf4819a5dbbc.js:15
(anonymous) @ _app-c29acf4819a5dbbc.js:15
```

I feel like I am missing some configuration detail. 

Any pointers are appreciated.

**Comment by pauldambra** [comment]
Hey,

Because your request is crossing origin from papermark.io to msft.io next-js rewrites can't act as a reverse proxy because they don't set CORS headers. The reverse proxy needs to set CORS headers to allow msft.io traffic (you can set to '*' to allow any origin to send data)

You can use next-js middleware instead of rewrites so that you can set the correct headers https://posthog.com/docs/advanced/proxy/nextjs-middleware

**Comment by mfts** [comment]
Thanks @pauldambra 

I'm leaving my solution here for posterity if someone stumbles on this issue: 

https://github.com/mfts/papermark/commit/d73f4309a2ffdb8e746f9415131daff607b80eb9
