### ISSUE TITLE
Posthog-js sending requests to /sessionRecording on user's own servers

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog-js#183]
I got a report from a user that they are seeing 404 requests to `/sessionRecording` on their own servers, when using app.posthog.com. So the requests are to theirdomain.com/sessionRecording

![image](https://user-images.githubusercontent.com/1727427/108836063-ad88c080-75d0-11eb-92e9-1742b9c90121.png)

@macobo any idea why this might be happening? I had a quick grep through the codebase but nothing obvious.

**Comment by macobo** [comment]
Not sure either. I wonder if this is happening during posthog-js or perhaps during playing back past recordings?

**Comment by mariusandra** [comment]
I got this locally a few times, happened during recording via posthog-js (I wasn't looking at a playback). Haven't been able to reproduce this reliably though.

**Comment by leojkwan** [comment]
running into this problem too, this bug is breaking production for me.  /s/gs5WICdat2WLXw3EYS3g/a/sessionRecording?compression=gzip-js&ip=1&_=1616597556618. typically my page route is s/[scheduleId]/a/[activityId]. This is only happening on SWR, when a user is logged in and attempting to hit the authenticated endpoint. 

https://superfitapp.com/s/gs5WICdat2WLXw3EYS3g/a/lWAf4kjYaS7CxuRTdd2H

**Comment by mariusandra** [comment]
I got it locally when leaving the standard posthog localhost app open in the background (but maybe not always?), however the request is always made to `"../sessionRecording"`. So if I'm on `/project/plugins`, the request always goes to `/project/sessionRecording`. Not sure if this helps much, but this is again some new information I didn't have before.

**Comment by anandvc** [comment]
I have this problem too.

**Comment by avorio** [comment]
I'm still seeing these errors all over ... using version 1.24.0 at the moment.
