### ISSUE TITLE
Inaccurate/unexpected session duration length (0 seconds)

### ISSUE THREAD

**Issue by chrishoyle** [PostHog/posthog-js#248]
I noticed in the /sessions dashboard that the session duration was often inaccurately shown to be 0 seconds. This was an unexpected result because I expected it to be equal to the rrweb recording length which showed a recording of several seconds or minutes long.

It appears that the current method of tracking session duration is calculated by the elapsed time between when the user's first recorded event and the last recorded event. The problem is that there is often only one event to initialize the session and no subsequent events and thus the session duration is calculated to be 0. An example of this is when a user goes directly to our blog post, spends some time reading it, and then closes the tab. 

I attempted to solve this by firing an event to posthog in a beforeunload callback (when the user exits the page). Unfortunately this doesn't reliably send an event to posthog. One workaround is to send stubbed capture events to posthog at a regular interval (ex. every few seconds). But this doesn't seem like the best solution. I at least expected the events recorded by /recorder.js to be counted in the session duration calculation

**Comment by mariusandra** [comment]
Can confirm that this is happening. To add a bit more context, the problem is most apparent for users who:

1. Open a page and create one `$pageview` event
2. Browse around the page for a few minutes without clicking anything
3. Leave without a proper `$pageleave` event getting a chance to be fired

Here's a perfect example. I'm searching for recordings over 10 minutes:

![image](https://user-images.githubusercontent.com/53387/123002353-20088200-d3b2-11eb-93c5-65db66ad54d4.png)

And here's one session with just three events in 3 seconds that showed up in the results:

![image](https://user-images.githubusercontent.com/53387/123002411-331b5200-d3b2-11eb-8d33-785d62554b64.png)

When I hit play, I can see that the user was on the site 21 minutes, mostly idle:

![image](https://user-images.githubusercontent.com/53387/123002524-4af2d600-d3b2-11eb-847c-b922af39384f.png)

**Comment by mariusandra** [comment]
PR https://github.com/PostHog/posthog/pull/4853 changes the interface to show the length of the session recording, if available (and larger than) the other calculated session length.

**Comment by mariusandra** [comment]
This should be solved now that PostHog/posthog#4853 is in
