### ISSUE TITLE
Sessions do not get recorded once user opts in

### ISSUE THREAD

**Issue by FilipPano** [PostHog/posthog-js#336]
**Describe the bug**
Sessions do not get recorded if initially the user is opted out from capturing events and later opted in.

**Steps To Reproduce**
1. Initialize posthog like this:
`posthog.init(token, {
    api_host: apiHost,
    autocapture: false,
    opt_out_capturing_by_default: true,
  });`
2. After initialization, opt the user in by calling:
`posthog.opt_in_capturing(); posthog.startSessionRecording();`

**Expected Behavior**
The sessions starts recording after `posthog.opt_in_capturing() `and `posthog.startSessionRecording()` are called.

**Actual Behavior**
The session is not being recorded.

**More Context On Business Requirement**
We don't want to record users' sessions until they give cookies consent, so initially we opt them out from capturing events, but once they confirm the cookies we'd like to start recording the session.

**Comment by chidg** [comment]
Similar issue here.
We are not doing session recording, but manually capturing certain events. We find that the `$opt_in` event is automatically sent when the user opts in, but no further events are sent until the the posthog instance is re-initialised with the opted-in state.

**Comment by chidg** [comment]
To add a bit more context after some more debugging - I've noticed that it's possible for the posthog instance to have both `has_opted_in_capturing` and `has_opted_out_capturing` false. ie, there is a third state where the user has not opted in or opted out of tracking. I guess this makes sense after thinking about it, because the user hasn't actually made a choice yet, but it is not obvious from the docs or intuitively (for me at least). It's also not obvious that even if the opted in value is false,  posthog will happily capture events as long as the opted out value is false. This is a problem for privacy conscious apps such as ours. What meaning does 'opting in' have in this context?

It appears that in my case initialising posthog with `opt_out_capturing_by_default: true`, as well as calling `posthog.opt_out_capturing()`, will prevent posthog from being able to capture events even once `posthog.opt_in_capturing()` is called.

**Comment by marcushyett-ph** [comment]
I think I’ve narrowed down the problem to [this if statement](https://github.com/PostHog/posthog-js/blob/7d5eefb21fb7634ae1a74d0fd099e730567aea89/src/posthog-core.js#L1288-L1290), looks like both clear_persistence and enable_persistence are set to true so it's not making it to the else_if and not re-enabling persistence.

**Comment by marcushyett-ph** [comment]
cc: @benjackwhite

**Comment by yaronlevi** [comment]
Any solution or explanation to this behaviour?

**Comment by pauldambra** [comment]
i added cypress tests to check this in response to a different issue https://github.com/PostHog/posthog-js/blob/b4b0050de81a2d009fbaa8b1f8df94e54311e7e5/cypress/e2e/opting-out.cy.ts#L94-L96

The solution is to explicitly start session recording after opting in

**Comment by jacobmpmc** [comment]
After attempting to solve this issue with the suggested calls to `startSessionRecording` I'm still facing issues with unreliable tracking. Looking at the implementation of these functions I can't locate anything that would re-start the request queue.

Given the proposed solution doesn't solve the issue and that starting session recording arguably shouldn't be required to get regular event capture working again I'd like to request the issue is re-opened.

I will add that the workaround from @paulcwatts with `_start_queue_if_opted_in` does work reliably in the mean time, however I'm rather concerned about relying on an undocumented method.

**Comment by pauldambra** [comment]
hey @jacobmpmc,

can you run through [the in-app support flow](https://us.posthog.com/#panel=support%3Asupport%3A%3Alow%3Atrue) please? the linked cypress test validates that things are working as we expected in a vanilla implementation - that doesn't, of course, mean that it is working for you :) 

> still facing issues with unreliable tracking

the first thing we always check here is if you're using a reverse proxy https://posthog.com/docs/advanced/proxy

**Comment by pauldambra** [comment]
(or if you do believe there's a bug here feel free to share more detail!)

**Comment by MichalMoravik** [comment]
As of 2025, this is totally buggy still. Tracking never starts after opting in unless I refresh web. And even then, sometimes it does tracking and sometimes it doesn't. It is inconsistent.

**Comment by pauldambra** [comment]
hey @MichalMoravik as above we still have an e2e test that validates this behaviour... are you able to create a minimal reproducible example?

there could be a bug here but we don't know what it is 😊

**Comment by jgoclawski** [comment]
@MichalMoravik @pauldambra - the e2e test tests only for toggling the `disable_session_recording` and this is actually working fine and is my current workaround.
What is still buggy (confirmed by me today) and there is no test for it is toggling the `opt_out_capturing_by_default` flag.

So what **doesn't work** is:

Init PostHog:
```
posthog.init('{{ buildEnv.posthogApiKey }}', {
  api_host: '{{ buildEnv.posthogApiHost }}',
  opt_out_capturing_by_default: true,
})
```
And later call:
```
posthog.opt_in_capturing();
posthog.startSessionRecording();
```

As of today this results in **no session recorded**.

My **workaround** is to use a different approach (using `disable_session_recording`) which is good enough for me.

Init PostHog:
```
posthog.init('{{ buildEnv.posthogApiKey }}', {
  api_host: '{{ buildEnv.posthogApiHost }}',
  disable_session_recording: true,
})
posthog.opt_out_capturing();
```
And later call:
```
posthog.opt_in_capturing();
posthog.startSessionRecording();
```

And then the events start flowing and the session gets recorder properly.

Hopefully this helps folks that struggled with it and maybe can result in some upstream fix as well :)

**Comment by oc8** [comment]
For me this config solves this problem:
`advanced_disable_feature_flags_on_first_load: true`

The /flags query was canceled by Nuxt
