### ISSUE TITLE
Identify and Reset behaviour are surprising

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog-js#512]
In this community slack thread https://posthogusers.slack.com/archives/C01GLBKHKQT/p1674160731821219

and this private slack thread https://posthog.slack.com/archives/C0374DA782U/p1674222079601469

We discovered something surprising

if you call the following chain of methods

```
posthog.reset()
posthog.capture('while anon')
posthog.identify('a user id')
posthog.capture('while identified')
```

You will get 4 person Ids and 4 distinct ids. If there were large gaps between these events this might be expected currently because of buffering issues we're still working through with person on events. But one after the other with almost no gaps this isn't expected behaviour.

If instead you call 

```
posthog.reset(true) // new person id and distinct id generated
posthog.capture('while anon') // event logged with those infos
posthog.identify('a user id') // new distinct id "a user id" associated with that Person
posthog.capture('while identified') // event logged with those infos
```

Where true is a flag to reset "device id" as well as "distinct id" then you get the expected flow.

The "problem" is here https://github.com/PostHog/posthog-js/blob/8891ba34ab14b10ea85a638250508bade69d56d4/src/posthog-core.ts#L1047

If the device id has not changed then we do not call identify with $anon_distinct_id and so no merge happens in ingestion.

Looking through history the only change for that method in 2022 was being converted to typescript on august 1st. 

And the behaviour to not reset device id on reset has been present since early in 2020. At that point in time we called identify if the distinct id had changed https://github.com/PostHog/posthog-js/blob/7e645ec1a8c353f53b01d8092d35fc39673a13fc/src/posthog-core.js#L924

And that behaviour was introduced in https://github.com/PostHog/posthog-js/pull/174 in Jan 28 2021

It's not clear to me if

* we're giving people the wrong advice and folk should call `posthog.reset(true)` on logout 
* the desired behaviour is correct and has been broken for 2 years
* assumptions in the pipeline are wrong from some point between 2 years ago and now

**Comment by pauldambra** [comment]
See this internal slack thread for more context https://posthog.slack.com/archives/C02E3BKC78F/p1674468527720569

This code is protecting against a situation like:

`identify('user')` -> `identify('staffUser')` -> `identify('user')`

In this case a staff user is impersonating a user and we don't want to merge 'user' and 'staffUser'

**Comment by pauldambra** [comment]
see https://squeak.cloud/question/421

**Comment by pauldambra** [comment]
And now identified here as well https://posthog.slack.com/archives/C046YCXSZ2Q/p1675288152535549

**Comment by pauldambra** [comment]
another user having this issue https://posthogusers.slack.com/archives/C01GLBKHKQT/p1675355052953359

**Comment by tiina303** [comment]
Since this is complicated ... obviously in addition to tests could we also add Harry style comments (i.e. explain why and what's happening, e.g. https://github.com/PostHog/posthog/blob/cfa94ebee3d1d4b113ad93cf1cfadc765fe7653f/plugin-server/src/worker/ingestion/event-pipeline/emitToBufferStep.ts#L76) for the whole identify function (given you've spent a bunch of time downloading that info to your brain lets make it easier for anyone else next time :) )

For example: 
(1) I'm not sure I understand what https://github.com/PostHog/posthog-js/blob/d93a42eaa3ed22a1b8aee323d796028adf8df11f/src/posthog-core.ts#L1024-L1039 means & can we remove https://github.com/PostHog/posthog-js/blob/d93a42eaa3ed22a1b8aee323d796028adf8df11f/src/posthog-core.ts#L1070-L1074 didn't see `ALIAS_ID_KEY` used anywhere.

(2) Could we explain what `deviceIdMarksForIdentify` is and why
