### ISSUE TITLE
"Cannot parse given Error object"

### ISSUE THREAD

**Issue by patricsteiner** [PostHog/posthog-js#643]
Anyone else encountering this error? Seems to happen quite randomly 🤔

```
message: "Cannot parse given Error object",
originalStack: "ZoneAwareError@http://localhost:4201/vendor.js:66340:29\nparse@https://eu.posthog.com/static/recorder-v2.js?v=1.57.2:18:12414\nd@https://eu.posthog.com/static/recorder-v2.js?v=1.57.2:18:17328..."
```

**Comment by iwasrobbed** [comment]
Yes, this happens very consistently when throwing an `AbortError` from an abort controller.

I'm assuming it has something to do with the setting where Posthog will record the user's actions around the time an error occurs (since the React error says `recording` in it).

<img width="548" alt="Screenshot 2023-08-17 at 5 33 03 PM" src="https://github.com/PostHog/posthog-js/assets/317671/3c3a35fb-c67d-4bda-be18-3715cb3ca1ca">
<img width="733" alt="Screenshot 2023-08-17 at 5 33 00 PM" src="https://github.com/PostHog/posthog-js/assets/317671/9b448e64-0487-45a9-a2a1-dc6e0f200c4b">
<img width="545" alt="Screenshot 2023-08-17 at 5 32 41 PM" src="https://github.com/PostHog/posthog-js/assets/317671/a7348b88-5803-4827-87aa-398a7f30fd9b">

**Comment by mmubasher** [comment]
Getting this error in 
ErrorStackParser.parse(ingest/node_modules/rrweb/es/rrweb/packages/rrweb/src/plugins/console/record/error-stack-parser)

`../node_modules/rrweb/es/rrweb/packages/rrweb/src/plugins/console/record/error-stack-parser.js in ErrorStackParser.parse at line 35:19`
```
        }
        else if (error.stack) {
            return this.parseFFOrSafari(error);
        }
        else {
            throw new Error('Cannot parse given Error object');
        }
    },
    extractLocation: function (urlLike) {
        if (urlLike.indexOf(':') === -1) {
            return [urlLike];
```
`../node_modules/rrweb/es/rrweb/packages/rrweb/src/plugins/console/record/index.js in unhandledrejectionHandler at line 78:44`
```
                payload = [
                    stringify('Uncaught (in promise)', logOptions.stringifyOptions),
                    stringify(event.reason, logOptions.stringifyOptions),
                ];
            }
            const trace = ErrorStackParser.parse(error).map((stackFrame) => stackFrame.toString());
            cb({
                level: 'error',
                trace,
                payload,
            });
```
`../../node_modules/@sentry/browser/esm/helpers.js in sentryWrapped at line 85:17`
```
      // Attempt to invoke user-land function
      // NOTE: If you are a Sentry user, and you are seeing this stack frame, it
      //       means the sentry.javascript SDK caught an error invoking your application code. This
      //       is expected behavior and NOT indicative of a bug with sentry.javascript.
      return fn.apply(this, wrappedArguments);
    } catch (ex) {
      ignoreNextOnError();
      withScope((scope) => {
        scope.addEventProcessor((event) => {
```

**Comment by mmubasher** [comment]
This error is not user impacting since thrown from RRWeb which is a dependancy by PostHog for screen capture. This issue is open in [PostHog repo #643](https://github.com/PostHog/posthog-js/issues/643).
posted this error to the [thread](https://github.com/PostHog/posthog-js/issues/643) for suggestion. If Posthog team does not deals with it, will report to rrweb.

**Comment by pauldambra** [comment]
sorry nobody replied here... that error line is no longer in the rrweb repo so i'll assume this is fixed as a result, feel free to reopen if needed
