### ISSUE TITLE
Early access / feature flag resets on initialisation

### ISSUE THREAD

**Issue by olliejm** [PostHog/posthog-js#668]
I've added the following site app to our SPA application: https://github.com/PostHog/early-access-features-app 

I'm using this to toggle an early access feature which is linked to a feature flag - then enabling something based on `useFeatureFlag` hook (also tried `posthog.isFeatureEnabled`).

This works fine - but once the SPA undergoes a hard refresh, it seems that this status is lost? I open the site app again and it's now deselected. It just stays that way too - as in, it doesn't appear to be waiting for the remote data.

Initially it also seemed that my user went missing from the early access members in posthog dashboard too, although now that doesn't seem to be the case.

**Comment by neilkakkar** [comment]
Hey @olliejm - I suspect this is because of ingestion delays: for the past hour, ingestion has been delayed, which means these property updates couldn't make it through to our servers in time, which meant hard refreshes removed this information.

I don't expect it to be a long running problem, mind trying again in an hour or so and let me know if this persists?

**Comment by olliejm** [comment]
no problem, I will try again shortly
