### ISSUE TITLE
Methods and flags which are unmentioned in the official docs - can I use them?

### ISSUE THREAD

**Issue by spodaras** [PostHog/posthog-js#759]
Hello all, I am currently evaluating PostHog for an application and I am wondering about two features that are not really documented in the docs but apparently they exist in the code. Now I am wondering: Can I make use of those, or is there a reason why there is no documentation? Are those deprecated or upcoming features and this is why they are only documented in code?

1. setPersonProperties()-method: I would like to add user properties once at the beginning of a session but keep the user anonymous. Even though the doc states that identify() can be called without an explicit user ID for frontend applications, in the code, setting the ID is mandatory. But there is another method, setPersonProperties() in the code, right after identify(). It allows to set user properties only, without an ID, which is exactly what I want - but why is there no "official" doc for this method. Its a method in the core:
https://github.com/PostHog/posthog-js/blob/28531c54d1e8ab1c825d44fa49ba6065925c9e97/src/posthog-core.ts#L1328
(I really don't want to provide user properties with every event I log, why repeat the same thing over and over again...)

2. Eventually, I have to mask text content of links in my application. I want to use autocapture though and wondered if it is possible to set the mask_all_text property to true? Again, I found this property in the sourcecode but not in the docs. Why is that so?
https://github.com/PostHog/posthog-js/blob/28531c54d1e8ab1c825d44fa49ba6065925c9e97/src/autocapture.ts#L231

**Comment by neilkakkar** [comment]
Hey @spodaras , could you please give me a link to the docs where you were looking for these? They are documented in the SDK docs: https://posthog.com/docs/libraries/js#overriding-server-properties

So, yes, both are supported, and you can use them :)

**Comment by benjackwhite** [comment]
@neilkakkar I think was referring to a slightly different method which is specifically for modifying how Feature Flags work.

`setPersonProperties` is pretty new which is why it isn't documented. It does exactly what you are asking for, setting properties against the current identity, without actually identifying them. It creates a special `$set` event that does this.
We will get that fixed ASAP to be in the docs.

And as he said, yes you can use the `mask_all_text`. There's no reason why it isn't documented so again we can get that updated.

**Comment by spodaras** [comment]
Thank both of you so much for the quick response! :)
