### ISSUE TITLE
Feature Flag giving the wrong value at the first time

### ISSUE THREAD

**Issue by YarinDay** [PostHog/posthog-js#867]
**Environment:**
"posthog-js": "^1.82.3"
"react": "^18.2.0",

When using the Website **on the first time**(incognito) I'm getting a wrong value for the Feature Flag, instead getting `true` I'm getting `false`.
After refreshing the page its giving the right value(`true`)-In order to tackle it I've added `onFeatureFlags` function but it still didn't work.

**Questions:**
How can I get the Feature Flag's right value at the first time?

I'm using this code:
```
posthog.onFeatureFlags(function () {
    console.log(posthog.isFeatureEnabled("is-super-admin")); 
    setIsSuperAdmin(posthog.isFeatureEnabled("is-super-admin"));
  });
```

**Comment by neilkakkar** [comment]
Hey @YarinDay most likely this is because when you first open the page, you're anonymous, so your user ID doesn't have the property defined. Then, you call `identify()` with the appropriate property which sets the right property and updates flags.

To confirm, try removing any properties on you feature flag and check if the issue persists.

If this isn't the case, mind raising this ticket via the in-app support button, and sending a link to your site?

If it is the issue, there's a few ways to fix it:

1. If the user is supposed to be identified on load, either call `identify()` in the onloaded callback, or use bootstrap to set the non-anonymous id
2. Bootstrap feature flags: https://posthog.com/docs/feature-flags/bootstrapping

**Comment by YarinDay** [comment]
Hey @neilkakkar ,
The problem was with the properties of the feature flag as you assumed.

I was considering both solutions you gave me, and I have few questions:
1. I didn't understand what is the onloaded callback and where should I put the `identify()`? Can you give me an example?
2. As for the bootstrap feature flags, as far as I understood in order to get the right values for the feature flags, I need to use server side code- Am I right? And if so, is there any other way I can do so via my client side?

Thank you!

**Comment by neilkakkar** [comment]
sorry, I meant `loaded`, see here: https://posthog.com/docs/libraries/js#config - this fires before flags are loaded. Call `identify()` in this callback.

If you're not server-side rendering, then indeed (1) is best.
